// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class OnlineshoppingexpereinceTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void onlineshoppingexpereince() {
    driver.Navigate().GoToUrl("https://www.amazon.in/");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.Id("twotabsearchtextbox")).Click();
    driver.FindElement(By.Id("twotabsearchtextbox")).Click();
    driver.FindElement(By.Id("twotabsearchtextbox")).SendKeys("camera");
    driver.FindElement(By.Id("twotabsearchtextbox")).SendKeys(Keys.Enter);
    {
      var element = driver.FindElement(By.Id("nav-link-accountList-nav-line-1"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".nav-cart-icon"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".nav-cart-icon")).Click();
    driver.FindElement(By.Name("submit.delete.C7e2360ed-7b91-40ee-8cfa-74e37b647af7")).Click();
    driver.FindElement(By.Id("twotabsearchtextbox")).Click();
    driver.FindElement(By.CssSelector("div:nth-child(7) .s-store")).Click();
    js.ExecuteScript("window.scrollTo(0,65)");
  }
}
